### ISSUE TITLE
Cant select blocks with WorldEdit

### ISSUE THREAD

**Issue by PatoCleiton11** [eaglerforge/EaglerForgeInjector#34] opened 2024-11-20 18:56 UTC
Im trying to use WorldEdit to make a empty world on the Nether (too lazy to find a done world, i dont even know how to import a nether world), i use the //wand command to get the Wand, but when i select a block clicking the Left Mouse Button, its just breaks the block, i saw some tutorials and i still doesnt know whats happening, can someone help me please? (im new to eaglercraft, eaglerforge and worldedit, so i doesnt know anything of these).

https://github.com/user-attachments/assets/43977aef-05e9-4eab-884f-df517bdfaf52

**Comment by PatoCleiton11** [comment] 2024-11-20 21:01
> Do you have any errors in the console?

no. i double checked it.

**Comment by STPv22** [comment] 2024-11-21 01:29
Try using the stable branch version. This also was custom made for eaglercraft, so tutorials for actual world edit aren't accurate.

**Comment by STPv22** [comment] 2024-11-22 02:03
sys://github/cabackping/radmanplays
(@radmanplays)

**Comment by OtterCodes101** [comment] 2024-11-22 16:26
@radmanplays can you find the last version it works in

**Comment by OtterCodes101** [comment] 2024-11-22 16:26
and try to reproduce the bug too

**Comment by OtterCodes101** [comment] 2024-11-22 16:26
if no i'll test it later

**Comment by radmanplays** [comment] 2024-11-22 16:35
> @radmanplays can you find the last version it works in

any version below u37

**Comment by OtterCodes101** [comment] 2024-11-22 17:00
Unable to reproduce this bug on eagler u42. World edit works just fine for me. What version of eagler are you injecting with? What browser are you using?

**Comment by radmanplays** [comment] 2024-11-22 17:14
> Unable to reproduce this bug on eagler u42. World edit works just fine for me. What version of eagler are you injecting with? What browser are you using?

it sometimes doesn't work if the tps is below 5

**Comment by ZXMushroom63** [comment] 2024-11-23 04:01
> > Unable to reproduce this bug on eagler u42. World edit works just fine for me. What version of eagler are you injecting with? What browser are you using?
> 
> it sometimes doesn't work if the tps is below 5

there's no way tps is gonna be changing enything, LCIs handlers are crammed inside the network stack, server's not even gonna get a chance to process the packet. When you see a block get broken, it's client side.

> Im trying to use WorldEdit to make a empty world on the Nether (too lazy to find a done world, i dont even know how to import a nether world), i use the //wand command to get the Wand, but when i select a block clicking the Left Mouse Button, its just breaks the block, i saw some tutorials and i still doesnt know whats happening, can someone help me please? (im new to eaglercraft, eaglerforge and worldedit, so i doesnt know anything of these).
> 
>  2024-11-20-15-47-01.mp4

also works fine in u40?
gonna wait till we get more information from @PatoCleiton11

**Comment by PatoCleiton11** [comment] 2024-11-24 20:45
i tried u42, u40 and u35, none of them worked, im using the mod "Worldedit.js" from the examplemods, and im using Google Chrome, do i need to use another browser? also do i need to hold a key in order to select a block?

**Comment by OtterCodes101** [comment] 2024-11-24 21:03
> i tried u42, u40 and u35, none of them worked, im using the mod "Worldedit.js" from the examplemods, and im using Google Chrome, do i need to use another browser? also do i need to hold a key in order to select a block?

chrome is fine
you do not need to hold a key

**Comment by ZXMushroom63** [comment] 2024-11-25 07:14
@PatoCleiton11 are you in singleplayer?

**Comment by radmanplays** [comment] 2024-11-25 14:38
> @PatoCleiton11 are you in singleplayer?

how would he have the wand then?

**Comment by ZXMushroom63** [comment] 2024-11-26 06:57
idk

**Comment by ZXMushroom63** [comment] 2024-12-25 05:39
closing. please ping if you want it reopened

**Closed by ZXMushroom63** 2024-12-25 05:39 UTC
Labels: bug, invalid

**Comment by Coolmathgamefactory** [comment] 2025-05-06 19:45
f

**Comment by Coolmathgamefactory** [comment] 2025-05-06 19:45
I need the download for U37
